// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: rbac.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	HasPermission(ctx context.Context, in *PermissionReq, opts ...grpc.CallOption) (Agent_HasPermissionClient, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) HasPermission(ctx context.Context, in *PermissionReq, opts ...grpc.CallOption) (Agent_HasPermissionClient, error) {
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], "/user.rbac.api.Agent/HasPermission", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentHasPermissionClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Agent_HasPermissionClient interface {
	Recv() (*PermissionResp, error)
	grpc.ClientStream
}

type agentHasPermissionClient struct {
	grpc.ClientStream
}

func (x *agentHasPermissionClient) Recv() (*PermissionResp, error) {
	m := new(PermissionResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	HasPermission(*PermissionReq, Agent_HasPermissionServer) error
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) HasPermission(*PermissionReq, Agent_HasPermissionServer) error {
	return status.Errorf(codes.Unimplemented, "method HasPermission not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_HasPermission_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PermissionReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).HasPermission(m, &agentHasPermissionServer{stream})
}

type Agent_HasPermissionServer interface {
	Send(*PermissionResp) error
	grpc.ServerStream
}

type agentHasPermissionServer struct {
	grpc.ServerStream
}

func (x *agentHasPermissionServer) Send(m *PermissionResp) error {
	return x.ServerStream.SendMsg(m)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.rbac.api.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HasPermission",
			Handler:       _Agent_HasPermission_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "rbac.proto",
}
